version: "3"

services:
  node:
    image: node:16.14
    container_name: blogs_api
    command: bash -c "npm install && npm run start"
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      JWT_SECRET: secretJWT
      API_HOST: "node"
      API_PORT: 3000
      NODE_ENV: "development"
    networks:
      - blogs_api_net
  db:
    container_name: blogs_api_db
    image: mysql:8.0.23
    # platform: linux/x86_64
    restart: always
    # retirar portas quando subir no servidor
    ports: 
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - blogs_api_net

networks:
  blogs_api_net:
    driver: bridge